PRAGMA foreign_keys = ON;

CREATE TABLE IF NOT EXISTS schema_migrations (
    version INTEGER PRIMARY KEY,
    applied_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS runs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    company TEXT NOT NULL,
    started_at TEXT NOT NULL,
    finished_at TEXT,
    success INTEGER NOT NULL DEFAULT 0,
    healthy INTEGER NOT NULL DEFAULT 0,
    is_baseline INTEGER NOT NULL DEFAULT 0,
    fetch_only INTEGER NOT NULL DEFAULT 0,
    request_url TEXT,
    http_status INTEGER,
    fetched_count INTEGER NOT NULL DEFAULT 0,
    us_count INTEGER NOT NULL DEFAULT 0,
    eligible_count INTEGER NOT NULL DEFAULT 0,
    new_count INTEGER NOT NULL DEFAULT 0,
    updated_count INTEGER NOT NULL DEFAULT 0,
    unchanged_count INTEGER NOT NULL DEFAULT 0,
    possibly_closed_count INTEGER NOT NULL DEFAULT 0,
    closed_count INTEGER NOT NULL DEFAULT 0,
    reopened_count INTEGER NOT NULL DEFAULT 0,
    review_count INTEGER NOT NULL DEFAULT 0,
    missing_posted_date_count INTEGER NOT NULL DEFAULT 0,
    missing_salary_count INTEGER NOT NULL DEFAULT 0,
    raw_archive_path TEXT,
    original_path TEXT,
    result_path TEXT,
    warnings_json TEXT NOT NULL DEFAULT '[]',
    error TEXT
);

CREATE TABLE IF NOT EXISTS jobs (
    source_job_id TEXT PRIMARY KEY,
    company TEXT NOT NULL,
    source_name TEXT NOT NULL,
    source_url TEXT,
    apply_url TEXT,
    canonical_url TEXT,
    source_adapter_version TEXT NOT NULL,
    title TEXT NOT NULL,
    normalized_title TEXT NOT NULL,
    team TEXT,
    department TEXT,
    employment_type TEXT,
    workplace_type TEXT NOT NULL,
    requisition_id TEXT,
    job_category TEXT,
    level TEXT,
    posted_at TEXT,
    posted_at_raw TEXT,
    posted_at_accuracy TEXT,
    updated_at TEXT,
    valid_through TEXT,
    closing_date TEXT,
    first_seen_at TEXT NOT NULL,
    last_seen_at TEXT NOT NULL,
    closed_at TEXT,
    fetched_at TEXT,
    location_raw TEXT,
    locations_json TEXT NOT NULL,
    primary_city TEXT,
    state TEXT,
    country TEXT,
    postal_code TEXT,
    street_address TEXT,
    latitude REAL,
    longitude REAL,
    distance_from_san_jose_miles REAL,
    location_filter_status TEXT NOT NULL,
    location_review_required INTEGER NOT NULL,
    description_raw_html TEXT,
    description_plain_text TEXT,
    responsibilities TEXT,
    minimum_qualifications TEXT,
    preferred_qualifications TEXT,
    required_qualifications TEXT,
    education_requirements TEXT,
    experience_requirements TEXT,
    other_requirements TEXT,
    benefits TEXT,
    travel_requirements TEXT,
    work_authorization_text TEXT,
    equal_opportunity_text TEXT,
    complete_job_posting_json TEXT NOT NULL,
    salary_text_raw TEXT,
    salary_min REAL,
    salary_max REAL,
    salary_currency TEXT,
    salary_period TEXT,
    compensation_type TEXT,
    bonus_text TEXT,
    equity_text TEXT,
    other_compensation_text TEXT,
    location_specific_compensation_json TEXT NOT NULL,
    is_us_job INTEGER NOT NULL,
    status TEXT NOT NULL,
    is_eligible_by_basic_filters INTEGER NOT NULL,
    eligibility_reason TEXT NOT NULL,
    baseline_in_scope INTEGER NOT NULL DEFAULT 1,
    content_hash TEXT NOT NULL,
    source_payload_hash TEXT NOT NULL,
    last_changed_at TEXT NOT NULL,
    change_type TEXT NOT NULL,
    consecutive_missed_runs INTEGER NOT NULL DEFAULT 0,
    parser_warning TEXT,
    fetch_warning TEXT,
    normalized_job_json TEXT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_jobs_status_eligible ON jobs(status, is_eligible_by_basic_filters);
CREATE INDEX IF NOT EXISTS idx_jobs_change ON jobs(change_type, last_changed_at);
CREATE INDEX IF NOT EXISTS idx_jobs_location_review ON jobs(location_review_required);
CREATE INDEX IF NOT EXISTS idx_jobs_posted_at ON jobs(posted_at);

CREATE TABLE IF NOT EXISTS job_versions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_job_id TEXT NOT NULL,
    run_id INTEGER NOT NULL,
    observed_at TEXT NOT NULL,
    change_type TEXT NOT NULL,
    content_hash TEXT NOT NULL,
    source_payload_hash TEXT NOT NULL,
    normalized_job_json TEXT NOT NULL,
    FOREIGN KEY(source_job_id) REFERENCES jobs(source_job_id),
    FOREIGN KEY(run_id) REFERENCES runs(id)
);

CREATE TABLE IF NOT EXISTS job_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    source_job_id TEXT NOT NULL,
    run_id INTEGER NOT NULL,
    event_at TEXT NOT NULL,
    event_type TEXT NOT NULL,
    details_json TEXT NOT NULL DEFAULT '{}',
    FOREIGN KEY(source_job_id) REFERENCES jobs(source_job_id),
    FOREIGN KEY(run_id) REFERENCES runs(id)
);
